### ISSUE TITLE
bug for deleteProcess

### ISSUE THREAD

**Issue by xiaoqinguo** [ergo-services/ergo#143]
![image](https://user-images.githubusercontent.com/9319187/216045082-4d1af51b-2320-4f72-990b-abc4c5877afe.png)

**Comment by halturin** [comment]
this code is correct. we don't care about the `p,` but we should clean up the internals related to the `p`

**Comment by xiaoqinguo** [comment]
p.lock and p.unlock must be called when iterate over p.aliases

**Comment by halturin** [comment]
> p.lock and p.unlock must be called when iterate over p.aliases

no needs. since the process is already removed from the core (above).
