### ISSUE TITLE
bug for (*process).UnregisterName

### ISSUE THREAD

**Issue by xiaoqinguo** [ergo-services/ergo#144]
![image](https://user-images.githubusercontent.com/9319187/216319955-9c96d816-eb69-488f-99b3-e700563898b8.png)

maybe should compare p.self with pid of prc.parent

**Comment by xiaoqinguo** [comment]
correct:
if prc.parent == nil || (prc.parent.parent.Self != p.self) {

**Comment by halturin** [comment]
This function is unregistering the name associated with the process. So the code is correct.
