### ISSUE TITLE
gen.TcpHandle Question

### ISSUE THREAD

**Issue by Echo-Cui-git** [ergo-services/ergo#152]
When I find that the incoming packet length of Calling HandlePacket is less than the value I want，I will return the value of left as len (packet), but why is the packet information not received last time overwritten when I receive the next package?

![截屏2023-03-29 14 29 06](https://user-images.githubusercontent.com/37608723/228445456-d26f32b5-5e75-4867-a46a-e93fd25183f0.png)
![截屏2023-03-29 14 29 21](https://user-images.githubusercontent.com/37608723/228445498-67e46c0d-659b-4c5c-9fe1-d47ec64cf079.png)

**Comment by Echo-Cui-git** [comment]
This result is completely different from the result returned in the case comment.

![image](https://user-images.githubusercontent.com/37608723/228446397-73812ea8-2eee-49a9-aaf3-0c2fded598a4.png)

**Comment by halturin** [comment]
If I do understand your question correctly... The main reason for returning `left`, `await` values is that you might receive a packet with the tail of your logical struct and the header of the next one. In this case, gen.TCP will append the tail data to the packet buffer and invoke HandlePacket with the packet containing the full logical struct while keeping the head data for the next packet.

**Comment by Echo-Cui-git** [comment]
i get it 
thank you

**Comment by Echo-Cui-git** [comment]
I send a slice -> [3 217 0 0 26 0 0 0 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
 
I send divided into two this slice 

3 seconds at intervals

e.g.
	dial.Write(slice[:4])
	time.Sleep(time.Second * 3)
	dial.Write(slice[4:])

but when  when call HandlePacket  first call 
This branch will be triggered:
`  
plen := len(packet)
	if plen < headLength {
		log.Errorf("packet too short %d", plen)
		return plen, headLength, gen.TCPHandlerStatusOK
	}
`
when I send slice[4:]. second call HandlePacket 
packet data is -> [26 0 0 0 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
![截屏2023-03-29 14 50 59](https://user-images.githubusercontent.com/37608723/228449927-e3d0fc40-b6ae-4fac-b119-a2a7faf820d6.png)

where is my first data?

**Comment by halturin** [comment]
not sure if I follow your example. could you please share your HandlePacket code and what you expected to see

**Comment by halturin** [comment]
You lose the first 4 bytes because of a timeout of socket reading which is 3 seconds by default. To see that, you can add a method HandleTimeout to your object `this`. The buffer is clearing on this event, that's where you lost these bytes. To fix your example just decrease your sending timeout.

I'm thinking of fixing it by keeping the data in the buffer even timeout is happening.

**Comment by halturin** [comment]
done in v2.2.3
