### ISSUE TITLE
node link problem? How to find

### ISSUE THREAD

**Issue by jiait** [ergo-services/ergo#165]
In the operating system of WIN 10, starting two Nodes with the same cookie, I want to use the Nodes() api interface to get all nodes with the same cookie, but sometimes I can get it and sometimes I can't. Could you tell me how to query this problem?

**Comment by halturin** [comment]
Method Nodes() returns the list of connected nodes

**Comment by jiait** [comment]
Nodes() returns empty, so I wonder if I can drill down to the bottom to get a clue？

**Comment by halturin** [comment]
It returns an empty list even being connected with the other nodes, right? If so, could you please share the way how it can be reproduced?

**Comment by jiait** [comment]
``func main() {
	StartGateNode(os.Args[1], "abc")
}

func StartGateNode(nodeName string, cookie string) {
	gateNode, err := ergo.StartNode(nodeName, cookie, node.Options{})
	if err != nil {
		slog.Fatal("start gate node error:%v", err)
	}
	slog.Info("node name:%s, cookie:%s, start ok", gateNode.Name(), cookie)
	slog.Info("nodes node :%v", gateNode.Nodes())
	common.Node.Wait()
}

**Comment by jiait** [comment]
[2023-08-11T00:18:18.684] INFO gateapp/main.go:21 node name:gate2@127.0.0.1, cookie:abc, start ok
[2023-08-11T00:18:18.698] INFO gateapp/main.go:22 nodes node :[]

**Comment by jiait** [comment]
Oh, my mistake, I misunderstood, sometimes I just sent a message and then the link was on, and I did not manually execute connect, which is always understood as automatic connection by default
