### ISSUE TITLE
node link problem？

### ISSUE THREAD

**Issue by jiait** [ergo-services/ergo#166]
erlang node links, for example, a ping c, b ping c, a nodes three node nodes, a ping c, b ping c, a nodes can find b, but ergo can not be tested like this at present, ergo must ping each other, or send messages to each other, in order to find?

**Comment by halturin** [comment]
Building full mesh (like erlang does it by default) is a perfect example of badly designed architecture.

**Comment by halturin** [comment]
Please, use "Discussion" for asking questions.
