### ISSUE TITLE
Support for Erlang/OTP 26

### ISSUE THREAD

**Issue by gargakshit** [ergo-services/ergo#168]
Connecting to, or from an Erlang/OTP 26 node fails.
The Erlang node logs

```
** 'node@hostname': Connection attempt from node ergo@hostname rejected since it cannot handle ["UNLINK_ID"].**
```

**To Reproduce**
1. Start a Erlang node running OTP26 with distribution enabled.
2. Connect from an ergo node.

**Environment (please complete the following information):**
 - Arch: aarch64
 - OS: macOS
 - Framework Version: v1.999.224 (v2.2.4)
 - GOMACPROCS: 8

**Comment by halturin** [comment]
thanks for the report. its already in the roadmap.

**Comment by halturin** [comment]
Erlang support will be distributed as a separate package. New version is available at github.com/ergo-services/proto and supports OTP23..27. This version is under BSL 1.1 license.

See 'examples' repo, branch v300. 
I also posted a quick benchmark results here https://x.com/halturin/status/1802801540216054040?s=46&t=a-KSHQlLDlsyfI8bjFDfng

**Comment by halturin** [comment]
Just released. see examples.
