### ISSUE TITLE
Node.Stop () and node.Wait () will immediately end the process

### ISSUE THREAD

**Issue by GameDaGongRen** [ergo-services/ergo#169]
As seen in the title.

Node.Stop () and node.Wait () will immediately end the process.

They don't wait for all processes to exit.

I don't think it's safe for some running processes.

I need to force Sleep to wait some time for all processes to exit safely.

So is it possible to record each process with sync.WaitGroup as it comes out of Spawn so that it can safely wait for their end during Stop?

**Comment by halturin** [comment]
Thanks for the report.

Yes, currently Node.Stop does force node termination without awaiting the running processes. The coming version 3.0 (planned to be released this fall) has Node.Stop(force bool). It works as you described.

**Comment by GameDaGongRen** [comment]
> Thanks for the report.
> 
> Yes, currently Node.Stop does force node termination without awaiting the running processes. The coming version 3.0 (planned to be released this fall) has Node.Stop(force bool). It works as you described.

Thank you for your reply.

I'm looking forward to the new version coming online.
