### ISSUE TITLE
PoolBehavior does not add restarted process to pool.monitors

### ISSUE THREAD

**Issue by fikomore** [ergo-services/ergo#171]
**Describe the bug**
When child process of Pool process is restarted with call process.Exit("restart") (for the first time it is restarted as expected) it is deleted from pool.monitors but the new child is not added to pool.monitors so when process.Exit("restart") is called the child process is not restarted.

**To Reproduce**
1. Create a pool with eg. 1 worker
2. call process.Exit("restart") from child process
3. When process is restarted call  process.Exit("restart") again
4. process is not restarted

**Expected behavior**
After each call process.Exit("restart") the process  should be restarted

**Environment (please complete the following information):**
 - Arch: x86_64
 - OS: Linux
 - Framework Version: 2.2.4

**Comment by fikomore** [comment]
This should fix the issue
![Screenshot from 2024-01-02 23-02-11](https://github.com/ergo-services/ergo/assets/33034864/1531ce38-0dc5-4680-bc53-090f80e0c9a7)

**Comment by halturin** [comment]
its been reworked, so not valid anymore
