### ISSUE TITLE
Why does Panic occur again in many Recover points, which causes the entire process to terminate?

### ISSUE THREAD

**Issue by Capybara-1** [ergo-services/ergo#196]
Why is it handled this way? This could lead to issues with the overall stability of the system.

![image](https://github.com/user-attachments/assets/3a6235cb-6ac3-4e6b-9848-c1807c505337)
![image](https://github.com/user-attachments/assets/14587082-b037-4930-9c2f-2f6e11415d6d)

**Comment by halturin** [comment]
ergo recovers only the gouroutines started by itself. if you start your own - make sure to handle panic. 

go's `recover` covers a single goroutine.

**Comment by Capybara-1** [comment]
> ergo recovers only the gouroutines started by itself. if you start your own - make sure to handle panic or write the correct code :)
> 
> go's `recover` covers a single goroutine.

I am using a Behavior started by Spawn

**Comment by halturin** [comment]
if you design your program properly, you dont need goroutines in most of the cases. actor model covers this need.

**Comment by halturin** [comment]
> > ergo recovers only the gouroutines started by itself. if you start your own - make sure to handle panic or write the correct code :)
> > go's `recover` covers a single goroutine.
> 
> I am using a Behavior started by Spawn

ergo should cover such panics then. otherwise, you use `go ....` somewhere inside of the actor callbacks

**Comment by Capybara-1** [comment]
> > > ergo recovers only the gouroutines started by itself. if you start your own - make sure to handle panic or write the correct code :)
> > > go's `recover` covers a single goroutine.
> > 
> > 
> > I am using a Behavior started by Spawn
> 
> ergo should cover such panics then. otherwise, you use `go ....` somewhere inside of the actor callbacks

I did not run my own goroutine using Go; the whole program only uses Actor.Spawn to start new Actors.

**Comment by halturin** [comment]
i can't help you without seeing the code

**Comment by halturin** [comment]
closing this report. create a new one with the way of reproducing the bug you got in your program. 

ps please, read the doc https://docs.ergo.services/actors/actor it covers how to use this framework.

**Comment by Capybara-1** [comment]
> closing this report. create a new one with the way of reproducing the bug you got in your program.
> 
> ps please, read the doc https://docs.ergo.services/actors/actor it covers how to use this framework.

I set breakpoints in your example project and found that the default Logger's Panic is merely a print statement instead of real panic logic. However, when I replaced the DefaultLogger with actual panic logic (like Zap's Panic), it caused this issue.

**Comment by halturin** [comment]
logger in ergo doesn't do the panic (and never should do this). its just a level for the error and must be used inside of panic handler.

**Comment by Capybara-1** [comment]
> logger in ergo doesn't do the panic (and never should do this). its just a level for the error and must be used inside of panic handler.

So, does that mean if I use a custom Logger, I cannot directly use Panic to cause a panic unless I wrap it myself and handle recover?
