### ISSUE TITLE
A suggestion regarding Panic handling for custom logging behavior.

### ISSUE THREAD

**Issue by Capybara-1** [ergo-services/ergo#198]
When the default Logger is disabled and a custom Logger is used, using Panic will cause the entire process to crash. 

It was discovered through debugging that a second Panic occurs within the Recover function in ProcessRun and other similar functions.

My suggestion is: could we remove the second Panic in the Recover function or directly replace it with an Error?

For specific details, please refer to the closed issue: https://github.com/ergo-services/ergo/issues/196#issue-2618724183.

I would like to hear the opinions or suggestions from everyone using it.

**Comment by halturin** [comment]
Please update the description. It's unclear what you mean for the others even referring to the #196. 

1. The use case with all the details and examples
2. Current behaviour 
3. What exactly you offering
