### ISSUE TITLE
Erlang 23 support

### ISSUE THREAD

**Issue by Noksa** [ergo-services/ergo#49]
Hello!

Do you have a plan to add support for Erlang 23?

Here is an error from Erlang 23 node when I try to call RPC on it from go:
```
➜ ~ erl -sname demo -setcookie 123
Erlang/OTP 23 [erts-11.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.2.1  (abort with ^G)
(demo@MBP-Alexandr)1> =ERROR REPORT==== 11-May-2021::09:24:34.078882 ===
** 'demo@MBP-Alexandr': Connection attempt from node 'test@MBP-Alexandr' rejected since it cannot handle ["BIG_CREATION"].**
```

**Comment by halturin** [comment]
Yeah, it doesn't support it yet, but it definitely will. Have no certain plan whether it be included in the next release. Will see.

**Comment by heri16** [comment]
Is Erlang v24 supported?

**Comment by halturin** [comment]
according to the README.md file 

> Support Erlang 22. (including fragmentation feature)

I'm working on support of 23/24 at this moment. Have no certain deadline. Maybe in a couple of months, I will release the new version.
