### ISSUE TITLE
Links within golang code to erlang docs are failing

### ISSUE THREAD

**Issue by gedw99** [ergo-services/ergo#76]
Links within golang code to erlang docs are failing also: https://github.com/ergo-services/ergo/blob/83c5934ff9/gen/application.go#L3

It would be nice if there was more docs. The erlang way of doing things looks really interesting.

**Comment by kluthen** [comment]
I still don't find any doc (either here or there on docs.ergo.services), did I miss something?

**Comment by gedw99** [comment]
can prob close this ?

**Comment by halturin** [comment]
yeah. closing.
