### ISSUE TITLE
empd port close abnormal

### ISSUE THREAD

**Issue by jiait** [ergo-services/ergo#87]
There are many time_waits on port 4369. The new node cannot be connected
![image](https://github.com/jiait/welcomeGame/blob/main/4369.png)

**Comment by halturin** [comment]
Thanks for the report. Could you please provide the way to reproduce this behavior?

**Comment by jiait** [comment]
When one node crashes unexpectedly, other nodes communicate to this node, and then this node restarts, but this node cannot be linked to other nodes. Try using Erlang nodes, and neither can be linked. At present, it is found that the node link is somewhat unstable. Do you need to add the NET Keepalive attribute

**Comment by halturin** [comment]
fixed in v2.0.2
