### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by jiait** [ergo-services/ergo#88]
Several problems were found: 
1. All the mailbox messages in the process are processed by coroutines. At present, there is a situation where the main process crashes unexpectedly, but the messages in the Mailbox can be processed in additional ways. 

![pid](https://user-images.githubusercontent.com/95669098/147743247-a087d92b-bf24-4ec5-aa8f-df9824319d1b.png)

2. Multiple Ergo nodes communicate, and some nodes restart back and forth. Accidentally, after the restart, nodes cannot connect to each other, and Erlang nodes cannot ping Ergo nodes

**Comment by halturin** [comment]
thanks for the report.

about the first case: the order of output doesn't guarantee the order of happening. that's how stdout works. you shouldn't rely on it. you may also want to add the option -ergo.norecover to see where the exact panic happened.

not sure about the second case. could you please provide the way how to reproduce it? i suppose it could relate to the EPMD problem you have reported early. 

PS: may I ask you to try the v210 branch? it has a lot of improvements in the network stack (including epmd feature)
